In [3]:
# Dependencies
import pandas as pd
import matplotlib.pyplot as plt
import scipy.stats as st
import numpy as np

In [12]:
# Read in the CDC Diagnosed data
diagnosed_df = pd.read_csv('CDC Diagnosed.csv')
diagnosed_df.head()

,Year,County_FIPS,County,State,Bivariate Tertile,Diagnosed Diabetes (Percentage),Obesity (Percentage),Newly Diagnosed Bivariate Tertile,Newly Diagnosed Diabetes (Rate per 1000),Newly Diagnosed Physical Inactivity (Percentage)
0,2018,1001,Autauga County,Alabama,HM,9.5,29.6,MH,9.1,23.8
1,2018,10001,Kent County,Delaware,HH,12.4,38.6,MH,10.5,29.7
2,2010,1001,Autauga County,Alabama,HH,9.2,28.2,HH,11.8,24.2
3,2016,10001,Kent County,Delaware,HH,11.2,33.7,HH,11.6,28.4
4,2014,1001,Autauga County,Alabama,HH,9.9,30.4,HH,10.5,24.3

In [27]:
# Display a statistical overview of the DataFrame.
diagnosed_df.describe()

,Year,County_FIPS,Diagnosed Diabetes (Percentage),Obesity (Percentage),Newly Diagnosed Diabetes (Rate per 1000),Newly Diagnosed Physical Inactivity (Percentage)
count,12561.000000,12561.000000,12561.000000,12561.000000,12561.000000,12561.000000
mean,2014.499642,30403.293528,8.367630,25.963681,9.724274,21.088719
std,2.958312,15149.373182,1.607645,5.318238,3.700566,4.394558
min,2010.000000,1001.000000,3.800000,10.500000,1.200000,8.800000
25%,2010.000000,18181.000000,7.200000,21.700000,7.300000,18.000000
50%,2014.000000,29179.000000,8.000000,26.000000,9.100000,20.600000
75%,2016.000000,45083.000000,9.200000,29.800000,11.400000,23.900000
max,2018.000000,56045.000000,17.900000,43.800000,51.700000,42.000000

In [26]:
print(diagnosed_df.columns)

Index(['Year', 'County_FIPS', 'County', 'State', 'Bivariate Tertile',
       'Diagnosed Diabetes (Percentage) ', 'Obesity (Percentage) ',
       'Newly Diagnosed Bivariate Tertile',
       'Newly Diagnosed Diabetes (Rate per 1000)',
       'Newly Diagnosed Physical Inactivity (Percentage) '],
      dtype='object')

In [24]:
diagnosed_df[["Year", "State", "Diagnosed Diabetes (Percentage) ", "Obesity (Percentage) ", "Newly Diagnosed Diabetes (Rate per 1000)", "Newly Diagnosed Physical Inactivity (Percentage) "]].head()

,Year,State,Diagnosed Diabetes (Percentage),Obesity (Percentage),Newly Diagnosed Diabetes (Rate per 1000),Newly Diagnosed Physical Inactivity (Percentage)
0,2018,Alabama,9.5,29.6,9.1,23.8
1,2018,Delaware,12.4,38.6,10.5,29.7
2,2010,Alabama,9.2,28.2,11.8,24.2
3,2016,Delaware,11.2,33.7,11.6,28.4
4,2014,Alabama,9.9,30.4,10.5,24.3

In [28]:
average_obesity = diagnosed_df["Obesity (Percentage) "].mean()
average_obesity

25.963681235570416

In [34]:
average_inactivity = diagnosed_df["Newly Diagnosed Physical Inactivity (Percentage) "].mean()
inactivity = "Newly Diagnosed Diabetes (Rate per 1000)"
inactivity_min = diagnosed_df["Newly Diagnosed Physical Inactivity (Percentage) "].min()
inactivity_max = diagnosed_df["Newly Diagnosed Physical Inactivity (Percentage) "].max()

inactivity_range = inactivity_max - inactivity_min
print(f"The range of values in '{inactivity}' is {inactivity_range}")

inactivity_group = diagnosed_df.groupby(["Year", "State"])["Newly Diagnosed Physical Inactivity (Percentage) "].agg([min, max])
inactivity_group["Range"] = inactivity_group["max"] - inactivity_group["min"]
print(inactivity_group)

average_inactivity

The range of values in 'Newly Diagnosed Diabetes (Rate per 1000)' is 33.2
                     min   max  Range
Year State
2010 Alabama        20.5  37.1   16.6
     Alaska         15.8  26.5   10.7
     Arizona        15.9  30.6   14.7
     Arkansas       18.0  38.5   20.5
     California     11.3  27.4   16.1
...                  ...   ...    ...
2018 Virginia       12.5  32.0   19.5
     Washington     11.5  22.5   11.0
     West Virginia  14.5  39.6   25.1
     Wisconsin      12.6  25.6   13.0
     Wyoming        10.7  27.0   16.3

[204 rows x 3 columns]

21.08871905103097

In [36]:
inactivity_year_diff = diagnosed_df.groupby("State")[["Year", "Newly Diagnosed Physical Inactivity (Percentage) "]].agg({"Year": ["min", "max"], "Newly Diagnosed Physical Inactivity (Percentage) ": ["min", "max"]})

inactivity_year_diff["Range"] = inactivity_year_diff[("Newly Diagnosed Physical Inactivity (Percentage) ", "max")] - inactivity_year_diff[("Newly Diagnosed Physical Inactivity (Percentage) ", "min")]
inactivity_year_diff["Change"] = inactivity_year_diff[("Newly Diagnosed Physical Inactivity (Percentage) ", "max")] - inactivity_year_diff[("Newly Diagnosed Physical Inactivity (Percentage) ", "min")]

print(inactivity_year_diff)

                      Year        \
                       min   max
State
Alabama               2010  2018
Alaska                2010  2018
Arizona               2010  2018
Arkansas              2010  2018
California            2010  2018
Colorado              2010  2018
Connecticut           2010  2018
Delaware              2010  2018
District of Columbia  2010  2018
Florida               2010  2018
Georgia               2010  2018
Hawaii                2010  2018
Idaho                 2010  2018
Illinois              2010  2018
Indiana               2010  2018
Iowa                  2010  2018
Kansas                2010  2018
Kentucky              2010  2018
Louisiana             2010  2018
Maine                 2010  2018
Maryland              2010  2018
Massachusetts         2010  2018
Michigan              2010  2018
Minnesota             2010  2018
Mississippi           2010  2018
Missouri              2010  2018
Montana               2010  2018
Nebraska              2010  2018
Nevada                2010  2018
New Hampshire         2010  2018
New Jersey            2010  2018
New Mexico            2010  2018
New York              2010  2018
North Carolina        2010  2018
North Dakota          2010  2018
Ohio                  2010  2018
Oklahoma              2010  2018
Oregon                2010  2018
Pennsylvania          2010  2018
Rhode Island          2010  2018
South Carolina        2010  2018
South Dakota          2010  2018
Tennessee             2010  2018
Texas                 2010  2018
Utah                  2010  2018
Vermont               2010  2018
Virginia              2010  2018
Washington            2010  2018
West Virginia         2010  2018
Wisconsin             2010  2018
Wyoming               2010  2018

                     Newly Diagnosed Physical Inactivity (Percentage)         \
                                                                   min   max
State
Alabama                                                           16.3  37.1
Alaska                                                            12.7  27.0
Arizona                                                           13.3  30.6
Arkansas                                                          16.3  38.5
California                                                        10.2  27.4
Colorado                                                           8.8  27.1
Connecticut                                                       15.9  25.6
Delaware                                                          21.4  29.7
District of Columbia                                              16.9  19.5
Florida                                                           14.4  42.0
Georgia                                                           13.0  32.3
Hawaii                                                            15.2  21.0
Idaho                                                             10.0  26.1
Illinois                                                          13.5  28.0
Indiana                                                           12.5  33.7
Iowa                                                              13.7  27.6
Kansas                                                            13.5  32.4
Kentucky                                                          13.4  37.5
Louisiana                                                         14.8  33.1
Maine                                                             13.7  31.6
Maryland                                                          13.9  31.0
Massachusetts                                                     13.4  27.8
Michigan                                                          12.6  28.9
Minnesota                                                         13.4  25.9
Mississippi                                                       14.9  36.9
Missouri                                                          13.9  38.8
Montana                                                           11.8  29.2
Nebraska                                                          13.2  32.3
Nevada                                                            13.7  28.6
New Hampshire                                                     16.4  28.0
New Jersey                                                        15.6  31.8
New Mexico                                                         9.8  30.8
New York                                                          13.9  32.4
North Carolina                                                    13.4  37.8
North Dakota                                                      14.4  29.9
Ohio                                                              14.4  34.0
Oklahoma                                                          14.0  34.9
Oregon                                                            11.0  24.6
Pennsylvania                                                      12.7  32.0
Rhode Island                                                      15.4  27.4
South Carolina                                                    13.9  34.5
South Dakota                                                      13.2  30.9
Tennessee                                                         12.6  33.0
Texas                                                             13.0  33.8
Utah                                                              11.2  26.3
Vermont                                                           13.3  25.2
Virginia                                                          12.5  35.4
Washington                                                         9.8  28.4
West Virginia                                                     14.5  39.6
Wisconsin                                                         12.6  27.8
Wyoming                                                           10.4  31.2

                     Range Change

State
Alabama               20.8   20.8
Alaska                14.3   14.3
Arizona               17.3   17.3
Arkansas              22.2   22.2
California            17.2   17.2
Colorado              18.3   18.3
Connecticut            9.7    9.7
Delaware               8.3    8.3
District of Columbia   2.6    2.6
Florida               27.6   27.6
Georgia               19.3   19.3
Hawaii                 5.8    5.8
Idaho                 16.1   16.1
Illinois              14.5   14.5
Indiana               21.2   21.2
Iowa                  13.9   13.9
Kansas                18.9   18.9
Kentucky              24.1   24.1
Louisiana             18.3   18.3
Maine                 17.9   17.9
Maryland              17.1   17.1
Massachusetts         14.4   14.4
Michigan              16.3   16.3
Minnesota             12.5   12.5
Mississippi           22.0   22.0
Missouri              24.9   24.9
Montana               17.4   17.4
Nebraska              19.1   19.1
Nevada                14.9   14.9
New Hampshire         11.6   11.6
New Jersey            16.2   16.2
New Mexico            21.0   21.0
New York              18.5   18.5
North Carolina        24.4   24.4
North Dakota          15.5   15.5
Ohio                  19.6   19.6
Oklahoma              20.9   20.9
Oregon                13.6   13.6
Pennsylvania          19.3   19.3
Rhode Island          12.0   12.0
South Carolina        20.6   20.6
South Dakota          17.7   17.7
Tennessee             20.4   20.4
Texas                 20.8   20.8
Utah                  15.1   15.1
Vermont               11.9   11.9
Virginia              22.9   22.9
Washington            18.6   18.6
West Virginia         25.1   25.1
Wisconsin             15.2   15.2
Wyoming               20.8   20.8